language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-javascript-kata' ]; then cd .. && eval "mv $currentfolder generator-javascript-kata" && cd generator-javascript-kata; fi

